ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MON-RR HH24:MI:SS';

SELECT * FROM timestamp_values;

ALTER SESSION SET TIME_ZONE = 'MST';

INSERT INTO timestamp_values
VALUES (2, LOCALTIMESTAMP(3), CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3));

SELECT * FROM timestamp_values;