prompt>Dropping users
DROP USER c##ap CASCADE;
DROP USER c##ex CASCADE;
DROP USER c##om CASCADE;

prompt>Creating users
CREATE USER c##ap IDENTIFIED BY ap DEFAULT TABLESPACE users;
CREATE USER c##ex IDENTIFIED BY ex DEFAULT TABLESPACE users;
CREATE USER c##om IDENTIFIED BY om DEFAULT TABLESPACE users;

prompt>Granting privileges
GRANT ALL PRIVILEGES TO c##ap;
GRANT ALL PRIVILEGES TO c##ex;
GRANT ALL PRIVILEGES TO c##om;