#  File: Euler2.py

#  Author: Stephen Rauner

#  Date Created: 4/7/17

#  Date Last Modified: 4/7/17

# Problem Description:
'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

											1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''

# /////////////////////////////////////////////////////////////////////////////////
# /////////////////////////////////////////////////////////////////////////////////
# /////////////////////////////////////////////////////////////////////////////////

def main():
	#lim = int(input("Enter limit: "))
	lim = 4*(10**6)
	tab = [0, 1, 1]
	tally = 0
	while tab[2] <= lim:
		if tab[2] % 2 == 0:
			tally += tab[2]
		tab[0] = tab[1]
		tab[1] = tab[2]
		tab[2] = tab[0] + tab[1]

	print (tally)

main()